
apiVersion: v2
name: helm-test
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: elasticsearch
    version: 17.0.2
    repository: https://charts.bitnami.com/bitnami
  - name: logstash
    version: 8.0.2
    repository: https://charts.bitnami.com/bitnami
  - name: kibana
    version: 9.1.5
    repository: https://charts.bitnami.com/bitnami

