apiVersion: v2
name: helm-test
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: elasticsearch
    version: 7.17.0
    repository: https://helm.elastic.co
  - name: logstash
    version: 7.17.0
    repository: https://helm.elastic.co
  - name: kibana
    version: 7.17.0
    repository: https://helm.elastic.co
