replicaCount: 1

image:
  repository: oracleinanutshell/oracle-xe-11g
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1521

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

persistence:
  enabled: false
