replicaCount: 1

image:
  repository: container-registry.oracle.com/database/free
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1521

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

persistence:
  enabled: false  # Ingen persistens; data går förlorad vid omstart

oracle:
  password: "oracle"  # Ställ in detta till det önskade lösenordet
  characterSet: "AL32UTF8"  # Exempel på teckenuppsättning
  enableArchiveLog: true
  enableForceLogging: true
