
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminserver
  labels:
    app: adminserver
spec:
  replicas: {{ .Values.adminserver.replicaCount }}
  selector:
    matchLabels:
      app: adminserver
  template:
    metadata:
      labels:
        app: adminserver
    spec:
      containers:
        - name: adminserver
          image: "{{ .Values.adminserver.image.repository }}:{{ .Values.adminserver.image.tag }}"
          ports:
            - containerPort: {{ .Values.adminserver.service.port }}

