apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: {{ include "helm-test.name" . }}
    chart: {{ include "helm-test.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    spring-boot: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.demo.containerPort }}
      protocol: TCP
  selector:
    app: {{ include "helm-test.name" . }}
    release: {{ .Release.Name }}
    component: demo

---

apiVersion: v1
kind: Service
metadata:
  name: adminserver
  labels:
    app: {{ include "helm-test.name" . }}
    chart: {{ include "helm-test.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.adminserver.containerPort }}
      protocol: TCP
  selector:
    app: {{ include "helm-test.name" . }}
    release: {{ .Release.Name }}
    component: adminserver
