
apiVersion: v1
kind: Service
metadata:
  name: demo
  spring-boot: "true"
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.demo.service.port }}

